### ISSUE TITLE
Simple doc update needed

### ISSUE THREAD

**Issue by RossMelbourne** [tawnkramer/donkey#18]
The --path argument is not required and causes an error.

See 'donkey createcar --path ~/d2'

**Comment by tawnkramer** [comment]
Are you sure? If you are using my fork, it is required

**Comment by RossMelbourne** [comment]
On a newly flashed SD card I did the following per the instructions:
git clone https://github.com/wroscoe/donkey donkeycar
pip install -e donkeycar
Should I have clicked the clone or download button to install donkeycar?

**Comment by RossMelbourne** [comment]
I guess it was pretty obvious but I missed that the git clone statement is pointing to the original donkeycar repo and not yours. I will start again using 'git clone https://github.com/tawnkramer/donkey donkeycar'

**Comment by tawnkramer** [comment]
You are welcome to use my fork. It is quite different than original repo. So be sure to check my docs for instructions.

**Comment by RossMelbourne** [comment]
Thanks Tawn. The docs on your main repo page are incorrect. See the git clone statement above. Also I think you need to add 'pip install picamera' and 'pip install Adafruit_PCA9685'.

**Comment by tawnkramer** [comment]
If you do a pip install -e .[pi] that will install pi related stuff.

**Comment by tawnkramer** [comment]
closing now. Please be sure you are running my fork.
