### ISSUE TITLE
ERROR: moviepy 1.0.0 has requirement imageio<3.0,>=2.5, but you'll have imageio 2.4.1 which is incompatible.

### ISSUE THREAD

**Issue by RossMelbourne** [tawnkramer/donkey#19]
Hi Tawn,
First off, THANK YOU for creating this version of donkeycar.  I have tried for hours to get a bluetooth gamepad to work with original donkey repo and with your code and instructions it worked first time!  Thanks again. 

My problem right now is setting up the donkey code on the PC (Mac in my case).  I am following instructions at:

https://github.com/tawnkramer/donkey/blob/master/docs/guide/install_software.md#install-donkeycar-on-mac.

All is well until I get to 'pip install -e .[pc]'.  Here I am seeing the following error which seems to prevent further steps too:

ERROR: moviepy 1.0.0 has requirement imageio<3.0,>=2.5, but you'll have imageio 2.4.1 which is incompatible.

Please help :-)

**Comment by tawnkramer** [comment]
You can remove moviepy from setup.py. That is only used in one command,
makemovie. Which you can do other ways on the Mac.

Good luck. And I will make a note to fix.

**Comment by tawnkramer** [comment]
I believe moviepy has fixed this.
