### ISSUE TITLE
Recording during AI?

### ISSUE THREAD

**Issue by RossMelbourne** [tawnkramer/donkey#20]
In config.py I have RECORD_DURING_AI = False set yet I am seeing:

/home/pi/env/lib/python3.5/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
recorded 10 records
recorded 20 records
recorded 30 records
recorded 40 records
recorded 50 records etc

**Comment by RossMelbourne** [comment]
The recording happens not during AI driving but when it drops out of Local Pilot and enters User mode. Not sure what is causing the drop out or what is causing recording to happen automatically since AUTO_RECORD_ON_THROTTLE = False.

**Comment by Bleyddyn** [comment]
I can test it when I get home, but I'm fairly sure it was working the last time I was at the track.

Do you have a myconfig.py that's overriding what's in config.py? 

Were there any error messages related to switching from Local to User mode? I've never encountered that problem.

**Comment by RossMelbourne** [comment]
I do not have a myconfig.py just config.py.   There are no messages other than the ones above regarding how many records were recorded.  BUT, I did get my DonkeyCar successfully training with this branch of the software.  Great job Tawn!!

**Comment by dlarue** [comment]
@RossMelbourne  if you do not have a myconfig.py file in your createcar directory then your software is way out of data or you are not using Tawn's fork.  The createcar utility leaves a myconfig.py file so you can put all your customizations there and leave config.py stock. This is so it can be over written without losing settings.

**Comment by Bleyddyn** [comment]
A quick test didn't show anything wrong on my car. However, I haven't ever seen the problem with it dropping out of local mode and into user mode without me hitting the button.

If re-creating the car directory doesn't fix it, we'll probably need more info.

**Comment by RossMelbourne** [comment]
I do have a myconfig.py.  I meant to say it was empty.  I am able to record during AI which is very useful for additional training.  If you cannot recreate recording in User mode with AUTO_RECORD_ON_THROTTLE = False then it must be something I have changed and you can close this.
