### ISSUE TITLE
AWS SageMaker

### ISSUE THREAD

**Issue by RossMelbourne** [tawnkramer/donkey#21]
Has anyone tried using this fork of Donkeycar with AWS SageMaker?  

In Jupyter notebook I am issuing the command:

!git clone https://github.com/tawnkramer/donkeycar ~/SageMaker/donkey

but it is asking for Username:

Cloning into '/home/ec2-user/SageMaker/donkey'...
Username for 'https://github.com/tawnkramer/donkeycar': 

Any ideas how to make this work please?

**Comment by blown302** [comment]
Sounds like a cloning issue. Can you clone any repo in that environment?

**Comment by RossMelbourne** [comment]
Yes, I could clone the original donkey repo but that had problems compiling.

**Comment by blown302** [comment]
Also, what are your intentions for SageMaker and donkey? If you just want to run a notebook both Tawn and I have notebooks we can share on Colab. If you want to run a job in SageMaker with donkey software I build a custom docker container.

**Comment by blown302** [comment]
Compiling? I haven't used that one for quite some time but I'm sure it's still python. Which is interpreted. 

If you want to use the notebook: was the clone directory empty? Try to the new directory. Also, try it locally.

**Comment by blown302** [comment]
Here is a link to a Colab notebook:

https://colab.research.google.com/drive/1i1Z6WSLt0Sx40T6xZ3ppXLW7mYStAyZO

In this one, I actually install donkey with pip. Should get you started and playing around with it. I believe colab still has free GPU.

**Comment by blown302** [comment]
Here is how I installed donkey

`!pip install git+https://github.com/tawnkramer/donkey.git`

**Comment by RossMelbourne** [comment]
I am completely new to doing ML in the cloud and chose SageMaker because the original Donkey repo had a few instructions for installing in AWS SageMaker. I will check into CoLab, thank you.  I assume you like it better than the other cloud services for ML.  As for compiling, I guess I should have said 'installing' :-).

**Comment by blown302** [comment]
Let me know how it works for ya. Honestly, I use colab because it's free with GPU. I use sagemaker to run Routine training jobs with an API call. 

However, I started a SageMaker Medium instance. Opened Jupyter and opened a new `terminal` from the new menu. ran `pip install git+https://github.com/tawnkramer/donkey.git` and it installed fine.

![image](https://user-images.githubusercontent.com/1878018/58071225-c8ebaf80-7b50-11e9-8f22-b96fcc06a372.png)

Then ran:
![image](https://user-images.githubusercontent.com/1878018/58071242-d6089e80-7b50-11e9-8611-df427fc6bc99.png)

I'd try that if you wanted to use SageMaker. I'm curious about any feedback you may have on the process.

Thanks,
Tom

**Comment by RossMelbourne** [comment]
In SageMaker, I was able to get past the previous hurdle by using your syntax:  !pip install git+https://github.com/tawnkramer/donkey.git.  However, then I receive the following error:
Cannot uninstall 'imageio'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by RossMelbourne** [comment]
In a CoLab notebook I had more success. I issued the following command as suggested:  !pip install git+https://github.com/tawnkramer/donkey.git.  Then I issued !donkey createcar which worked!  Thank you.  Since CoLab appears to be working and is free (I am yet to try training so I am assuming Tensorflow will work) I can abandon SageMaker.
