### ISSUE TITLE
Install dependencies not working 

### ISSUE THREAD

**Issue by tbroehm** [tawnkramer/donkey#25]
If I try to run the following command on my Raspberry PI 4B out from the docs:

sudo apt-get install build-essential python3 python3-dev python3-pip python3-virtualenv python3-numpy python3-picamera python3-pandas python3-rpi.gpio i2c-tools avahi-utils joystick libopenjp2-7-dev libtiff5-dev gfortran libatlas-base-dev libopenblas-dev libhdf5-serial-dev libgeos-dev git ntp

Get the following errors. Could somebody of you fix the broken versions or just tell me what to do to fix it on my Rasberry ?
Thanks a lot.

Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libavahi-client3 armhf 0.7-4+b1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:2 http://raspbian.raspberrypi.org/raspbian buster/main armhf avahi-utils armhf 0.7-4+b1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:4 http://raspbian.raspberrypi.org/raspbian buster/main armhf git-man all 1:2.20.1-2+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:5 http://raspbian.raspberrypi.org/raspbian buster/main armhf git armhf 1:2.20.1-2+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:6 http://raspbian.raspberrypi.org/raspbian buster/main armhf libsndfile1 armhf 1.0.28-6
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:7 http://raspbian.raspberrypi.org/raspbian buster/main armhf libx11-xcb1 armhf 2:1.6.7-1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:8 http://raspbian.raspberrypi.org/raspbian buster/main armhf libjpeg62-turbo-dev armhf 1:1.5.2-2+b1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:9 http://raspbian.raspberrypi.org/raspbian buster/main armhf libjpeg-dev all 1:1.5.2-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:10 http://raspbian.raspberrypi.org/raspbian buster/main armhf libjs-jquery all 3.3.1~dfsg-3
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:11 http://raspbian.raspberrypi.org/raspbian buster/main armhf libopenjp2-7 armhf 2.3.0-2+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:12 http://raspbian.raspberrypi.org/raspbian buster/main armhf libopenjp2-7-dev armhf 2.3.0-2+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:13 http://raspbian.raspberrypi.org/raspbian buster/main armhf libpython3.7-dev armhf 3.7.3-2+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:14 http://raspbian.raspberrypi.org/raspbian buster/main armhf libwebp6 armhf 0.6.1-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:15 http://raspbian.raspberrypi.org/raspbian buster/main armhf libtiff5 armhf 4.1.0+git191117-2~deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:16 http://raspbian.raspberrypi.org/raspbian buster/main armhf libtiffxx5 armhf 4.1.0+git191117-2~deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:17 http://raspbian.raspberrypi.org/raspbian buster/main armhf libtiff-dev armhf 4.1.0+git191117-2~deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:18 http://raspbian.raspberrypi.org/raspbian buster/main armhf libtiff5-dev armhf 4.1.0+git191117-2~deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:19 http://raspbian.raspberrypi.org/raspbian buster/main armhf libwebpdemux2 armhf 0.6.1-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:20 http://raspbian.raspberrypi.org/raspbian buster/main armhf libwebpmux3 armhf 0.6.1-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:21 http://raspbian.raspberrypi.org/raspbian buster/main armhf python3.7-dev armhf 3.7.3-2+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:22 http://raspbian.raspberrypi.org/raspbian buster/main armhf python3-lxml armhf 4.3.2-1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:23 http://raspbian.raspberrypi.org/raspbian buster/main armhf python3-pil armhf 5.4.1-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/a/avahi/libavahi-client3_0.7-4+b1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/a/avahi/avahi-utils_0.7-4+b1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/c/curl/libcurl3-gnutls_7.64.0-4_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/git/git-man_2.20.1-2+deb10u1_all.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/git/git_2.20.1-2+deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libs/libsndfile/libsndfile1_1.0.28-6_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libx/libx11/libx11-xcb1_1.6.7-1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libj/libjpeg-turbo/libjpeg62-turbo-dev_1.5.2-2+b1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libj/libjpeg-turbo/libjpeg-dev_1.5.2-2_all.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/j/jquery/libjs-jquery_3.3.1~dfsg-3_all.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/o/openjpeg2/libopenjp2-7_2.3.0-2+deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/o/openjpeg2/libopenjp2-7-dev_2.3.0-2+deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/python3.7/libpython3.7-dev_3.7.3-2+deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libw/libwebp/libwebp6_0.6.1-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/t/tiff/libtiff5_4.1.0+git191117-2~deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/t/tiff/libtiffxx5_4.1.0+git191117-2~deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/t/tiff/libtiff-dev_4.1.0+git191117-2~deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/t/tiff/libtiff5-dev_4.1.0+git191117-2~deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libw/libwebp/libwebpdemux2_0.6.1-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libw/libwebp/libwebpmux3_0.6.1-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/python3.7/python3.7-dev_3.7.3-2+deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/l/lxml/python3-lxml_4.3.2-1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/pillow/python3-pil_5.4.1-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by dlarue** [comment]
Looks to me like you either don't have the rPi on the Internet so it can't connect to update server(  http://raspbian.raspberrypi.org ) or that update server is no longer the URI address to be using.

Which is it?

**Comment by tbroehm** [comment]
Just do a fresh install as out from the docs and you will run into the same. Internet is fine as other installs work without problem. Help is kindly appreciated.

**Comment by dlarue** [comment]
What is the output from updating the repository list?  ( that would be doing 'sudo apt update' )

**Comment by tbroehm** [comment]
SOLVED.
I started from scratch with the newest Raspberry PI OS from https://www.raspberrypi.com/software/ instead of the latest raspbian (Buster) mentioned in the Donkey Car docs.
I am now in the calibration process for steering and throttle...
Thanks for your help.
